### PR TITLE
[[ Bug 20449 ]] Fix buggy rendering of arcs on Windows

### PR DESCRIPTION
**Pull request by livecodeian**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecodeian - I guess this deserves two questions...

1) What does SK_NO_ANALYTIC_AA actually do (i.e. what is analytic aa)?

2) Why is this confined to Windows?

**Comment by livecodeian** [comment]
@runrevmark 

1. Google can answer that question better than I can. Seems to have been introduced to Skia as an alternative (though now default) antialiasing codepath.

2. I haven't found a cause for that yet - may be compiler specific, though that's really just speculation.

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 0c8a37e

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 0c8a37eba48225311956bf338d1eed7bcf3c2314

**Pull request merged**
