### PR TITLE
Use the correct revsecurity.def file when building revsecurity.dll

### PR DESCRIPTION
**Pull request by livecodefraser**
The one in the thirdparty repo was out of date and referenced
symbols no longer provided by OpenSSL.

### CODE REVIEW

**Comment by peter-b** [comment]
Can we delete the one from thirdparty to avoid this confusion happening in the future?

**Comment by livecodefraser** [comment]
That's why this PR is -3,858 lines :wink:

**Comment by peter-b** [comment]
Oh yes, curse GitHub hiding things that it's too pathetic to attempt to display.

**Comment by peter-b** [comment]
@livecode-vulcan review ok 8a15234

**Comment by mwieder** [comment]
As much as I hate submodules, thank you for bringing this up to date.
I also notice the comment on VCManifestTool: it's been a while since I've had to deal with msvc - is this a problem for the build? I glanced at the docs at https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.vcprojectengine.vcmanifesttool.aspx?cs-save-lang=1&cs-lang=cpp#code-snippet-1 and it seems pretty useless for the security dll.

**Comment by livecodefraser** [comment]
Note: this needs to be merged after OpenSSL 1.0.1s (https://github.com/livecode/livecode/pull/3768) is backported into the 6.7 prebuilt repo - the revsecurity.def file is currently missing from 6.7 and will need to be added then.

@mwieder I don't see a comment about VCManifestTool?

**Comment by mwieder** [comment]
@livecodefraser line 228 of libopenssl.gyp

**Comment by livecodefraser** [comment]
Ah, the original Visual Studio project file for revsecurity had a manifest listed for revsecurity but the file doesn't exist in the repo. And, as you say, there's not much in a manifest file that is relevant to revsecurity.

**Pull request merged**
