### PR TITLE
Update our LCMS header to LCMS2 version 2.7

### PR DESCRIPTION
**Pull request by livecodefraser**
Part of https://github.com/livecode/livecode/pull/3742 - these cannot be merged separately without breaking things.

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodefraser Did you mean livecode/livecode#3742

**Comment by livecodefraser** [comment]
Typo? What typo? :wink:

**Comment by peter-b** [comment]
Looks good to me.

**Comment by peter-b** [comment]
@livecode-vulcan review ok c24821a

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok c24821aad65f017649772673e9185fab284b8f2a

**Pull request merged**
