### PR TITLE
Merge release 8.1.2 10.11.2016

### PR DESCRIPTION
**Pull request by livecodepanos**
Clean merge

### CODE REVIEW

**Comment by livecodepanos** [comment]
self review:

@livecode-vulcan review ok 8b6ae30

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 8b6ae30a6d481af28a3c647271e58359acf2a0d2

**Comment by livecodepanos** [comment]
Re-merged `release-8.1.2` to include the missing dependencies

**Comment by livecodepanos** [comment]
clean re-merge, self-review:

@livecode-vulcan review ok dcd247c

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok dcd247c30a501a560a25ec659a482c6adc7bd8cd

**Pull request merged**
