### PR TITLE
[[ ARM64 ]] Update the config for libXML and libMySQL to handle arm64

### PR DESCRIPTION
**Pull request by livecodesebastien**

### CODE REVIEW

**Comment by livecodesebastien** [comment]
@runrevmark, can you review this? We actually need it for ARM64 compilation

**Comment by runrevmark** [comment]
The defining of x86_64 when the target is an ARM processor is a little dodgy so you should check that any uses of such in the mysql client lib source isn't depending on x86-only things.

**Comment by livecodesebastien** [comment]
From a search inside the whole directory, this macro is only used in the file my_global.h (l. 129)
`#  if defined(__i386__) || defined(__ppc__) || defined(__arm__)`
`#    define SIZEOF_CHARP 4`
`#    define SIZEOF_LONG 4`
`#  elif defined(__x86_64__) || defined(__ppc64__)`
`#    define SIZEOF_CHARP 8`
`#    define SIZEOF_LONG 8`
`#  else`
`#    error Building FAT binary for an unknown architecture.`
`#  endif`
Compiling beforehand was obviously throwing the error `Building FAT binary for an unknown architecture.`

**Comment by runrevmark** [comment]
Okay - I suggest patching that file to do

```
#elif defined(__x86_64__) ... || defined(__aarch64__)
```

It's cleaner and more accurate :)

**Comment by livecodesebastien** [comment]
Sure - I didn't want to mess up with my_config.h, but that's a config file as well, nothing more.
I'll close the branch though, as it should go in develop-6.7, not develop

**Pull request closed without merging**
