### PR TITLE
Update cairo to most recent version (1.15.2)

### PR DESCRIPTION
**Pull request by runrevmark**
This patch updates the cairo library to the latest available.

It is split into several commits to help submit suitable changes upstream at a later date.

The changes specific to revpdfprinter are maked with 'revpdfprinter additions' lines before and after.

### CODE REVIEW

**Comment by peter-b** [comment]
@runrevmark Do you have a recipe to reproduce the error caused by not setting `surface->is_clear = FALSE`? Got most of the way to writing an upstream patch... there's no time like the present!

**Comment by runrevmark** [comment]
Of the commits...

The Adobe CMYK fix is probably suitable for upstream - it fixes a bug Trevor noticed with certain CMYK images appearing inverted.

The ability to configure PDF metadata / bookmarks / outline is probably suitable for upstream - it adds a feature which is not there currently.

The image surface with mimedata one is a little more tricky. Cairo will discard attempts to paint with surfaces which have no content. As we only use cairo to print to pdf, we don't care about providing actual pixels for images (the PDF format we emit supports all the features of cairo we use directly without rasterization), we just want cairo to emit the actual encoded image data (original). So, the patch as stands probably isn't correct for a wider audience - it would probably need some discussion with the cairo dev's decide how such an option (to not trivially reject surfaces with no pixel content) should be handled.

**Comment by peter-b** [comment]
Looks good to me :+1:

**Comment by peter-b** [comment]
@livecode-vulcan review ok f983de9

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok f983de9e3cd3cb4a4e26247bbc9baa5dba239e07

**Comment by peter-b** [comment]
@runrevmark I think there's a missing `break` in `_cairo_pdf_value_init()` in `cairo-pdf-ext.c`.

**Comment by peter-b** [comment]
@livecode-vulcan review ok 79864a4

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 79864a41bf0007927e5c0010c376f8e9be6fc4de

**Pull request merged**
