### PR TITLE
Update libSkia to upstream (Dec 2016)

### PR DESCRIPTION
**Pull request by livecodefraser**
See libskia/git-revision.txt for commit hash.

Updates Skia to a much more recent upstream version. All changes except those to libskia/git-revision.txt and libskia/libskia.gyp have just been pulled from the upstream without changes.

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok d817560

I have merged these changes into the `integration-vs2015` branch.

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok d817560d7d8fa4f6a94c628f5e6777d7a9c863b8

**Comment by livecodeian** [comment]
@livecode-vulcan review ok 608e804

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeian ok 608e8042166b663975cb60fd50a59b2cd41747b0

**Pull request merged**
