### PR TITLE
[[ Bugfix 14413 ]] RevZip: add UTF-8 understanding on Windows

### PR DESCRIPTION
**Pull request by livecodesebastien**

### CODE REVIEW

**Comment by livecodestephen** [comment]
This may be the wrong place to raise this but ....

This version of libzip is quite old &mdash; I think it's getting on for 10 years! &mdash; and there have been lots of bug fixes and enhancements upstream.  Is there any plan to update to a newer version?  Any changes to our libzip will mean that we diverge further from upstream and could make any future pull from upstream harder.

**Comment by runrevmark** [comment]
We've patched libzip to support progress reports (as previously discussed) thus the amount of work to move the current version forward is a great deal more than small patches to support the feature-set revzip currently has and uses. Given that we are aiming towards LCB for wrapping third-party libraries it seems a little silly to waste engineering time on updating revzip (in C++/C), when it would be much easier to replace it with a new LCB-based version using the latest and greatest libzip in the near future.

(This is of course, assuming we can find a better way to do 'progress reporting'!)

**Comment by runrevmark** [comment]
Okay I think I see code here to write a UTF-8 filename (and set the appropriate bit) - what about reading in archives?

Also, what is the impact of that bit on other platforms?

**Comment by livecodesebastien** [comment]
The bit setting is done on every platform, since we are currently (7.0.3) setting a UTF-8 encoded name to the item on Mac and Linux (and the current behaviour - 7.0.3 - is wrong, since the UTF-8 bit is not set).
I don't think that there is any issue concerning the reading phase, as we currently consider the input as UTF-8 on all platforms. That's is not exactly right, but decoding native text as UTF-8 does not cause any harm in the end.

**Comment by runrevmark** [comment]
Well the latter can't be true - what happens if we are reading a zip file created from another tool?

We need to correctly interpret the bit and convert appropriately otherwise zips created outside of LiveCode won't work correctly.

We need to make sure that:
   1) zip created with LC can be correctly read with LC
   2) zip created outside of LC can be correctly read with LC (for each platform)
   3) zip created indside of LC can be correctly read outside of LC (for each platform)

**Comment by peter-b** [comment]
> 2) zip created outside of LC can be correctly read with LC (for each platform)

This is arguably not reliably possible (.zip files created with WinZip on a Windows installation with Shift-JIS as the system encoding, for example).

**Comment by livecodesebastien** [comment]
If the zipper is correctly implemented, it should use the UTF-8 encoding for any string containing a Unicode (or even non-ASCII standard) character, and set the UTF-8 bit. In that case, the branch allows one to open the archive, and list the items included, had them Unicode characters.
We encode every single string (archive filename and each archive item) using UTF-8, and the UTF-8 bit is set; 7zip is perfectly able to open an archive containing Unicode items, created from this branch.
And LiveCode is able to correctly read the archive it created, since it only uses UTF-8 string for reading / writing.
(I checked all of that before issuing the pull request).

**Comment by runrevmark** [comment]
Okay - one final case to check - what happens if you create a zip file with an _older_ version of LiveCode's revZip with filenames containing accented chars?

We can't do much about the general case (as @peter-b points out) but we can at least make sure we retain 100% compatibility with older versions of revZip...

(By 'older' I mean pre-7.0 - i.e. non unicode in any way version :))

**Comment by livecodesebastien** [comment]
Hm... As for now, `revZipEnumerateItems` (for instance) is declared as a UTF-8 external function, from 7.0 onwards.
The problem is that is must return a UTF-8 encoded string; and in an archive saved in 6.7, if an item string is native (as in été.png), the accented characters are deleted when the items are listed in 7.0.3 (and as well in this branch). 
Now, that's an existing bug in 7.0. Should we implement a native -> UTF-8 char conversion function in revzip.cpp? That seems to be the only viable solution when having chars > 128

**Comment by runrevmark** [comment]
I suggest implementing an external hook function that converts from the 'native' encoding to UTF-8 thus avoiding having to replicate code in revZip. Then, in any file entries which don't have the UTF-8 bit set, apply that conversion to the filename. Perhaps:

```
char *ConvertCStringFromNativeToUTF8(const char *native, int *r_success)
```

(caller frees the result)

**Comment by livecodesebastien** [comment]
That's a good suggestion - will add this.

**Comment by runrevmark** [comment]
I guess we should have the opposite way round for completeness too - `ConvertCStringFromUTF8ToNative` is probably a reasonably consistent choice.

**Pull request merged**
